version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    depends_on:
      - postgresdb
    networks:
      - app-go
    ports:
    - 3005:3000

  postgresdb:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5435:5432'
      volumes:
        - ./tmp/pg_data:/var/lib/postgresql/data
      networks:
        - app-go
volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  app-go:
    driver: bridge
